apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configmaps-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-60"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ashutosh-18k92/gitops-v2.git
    targetRevision: HEAD
    path: configmap
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
