apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-vrs-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ashutosh-18k92/gitops-v2.git
    targetRevision: HEAD
    path: platform/ingress-virtual-services
  destination:
    server: https://kubernetes.default.svc
    namespace: super-fortnight
  syncPolicy:
    automated:
      prune: true
      selfHeal: true